### ISSUE TITLE
Cannot read property 'bringToFront' of undefined

### ISSUE THREAD

**Issue by shmuel-web** [Synthetixio/synpress#194]
Hi

thanks for this amazing repo

I am having an issue with the initial setupMetamask phase
after the secret pass, phrase || password step has finished

<img width="927" alt="Screen Shot 2021-08-13 at 13 01 56" src="https://user-images.githubusercontent.com/13344801/129340719-24da5c60-0761-483d-943b-166e544914ea.png">

might have missed something
should I configure "bringToFront" anywhere?

Thanks

**Comment by drptbl** [comment]
Hey @shmuel-web, thanks for reporting. I will take a closer look over the weekend and try to help you.

Cheers,
Jakub.

**Comment by drptbl** [comment]
Hey @shmuel-web, I'm not sure why does it happen for you, but I've just integrated `synpress` with a repository from scratch and it works just fine, you can see an example here:
https://github.com/vbstreetz/synth-scan/commit/40f1e32a7fb139a1af688e4c95c6999d136d09e0

Your issue is related to the fact that when synpress is started, there are 2 tabs open. First one is with your main application which is going to be tested and the second one is metamask window where initial setup for metamask is done. After metamask setup is done, I'm triggering `bringToFront()` function to get back to the first tab with your main app which is going to be tested.

I suspect that this issue is related to the fact that:
1. Either you did something on your PC when tests were running. Please let them run and watch patiently without interfering with your mouse on keyboard while they run.
2. I can't see secondary tab on your screenshot with metamask, but you said that metamask setup went through just fine. Have you closed your secondary tab manually? Please don't interfere with your tests when they run.

<img width="1183" alt="Screenshot 2021-08-13 at 14 56 33" src="https://user-images.githubusercontent.com/8177587/129360381-735938f1-d721-4ac4-8857-5d5aefba0e16.png">

Let me know if you have any more questions.

Thanks,
Jakub.

**Comment by shmuel-web** [comment]
Hey thanks for the quick reply

cloned the repo you mentioned

and managed to run the e2e tests 
properly

Started looking for something I was missing in my setup

noticed you are using the ```synpress run``` 
and I was using ```synpress open``` 

so I switched run with open on your repo and boom

<img width="927" alt="Screen Shot 2021-08-13 at 17 24 18" src="https://user-images.githubusercontent.com/13344801/129372524-355ccc61-f0b5-4e7e-bd41-9cea6f354752.png">

so the issue is probably caused by the open command 

you can reproduce the issue if you like 

thanks again

**Comment by drptbl** [comment]
@shmuel-web thanks for letting me know! I will take a look in to it 👍 

Cheers,
Jakub.
