### ISSUE TITLE
Metamask 10+ support

### ISSUE THREAD

**Issue by drptbl** [Synthetixio/synpress#255]
Add support for metamask post-EIP1559 (metamask >9).

**Comment by kathodler** [comment]
This was the first blocker that I came across here otherwise working with this was a dream. I got here because I am forking mainnet to test preexisting tokens that were launched after eip1559. Would be good if there was a way to download selectors for versions of metamask to a file or scripts that gets read so that support can be enabled buy updating a selectors file or even installing an npm package.

**Comment by drptbl** [comment]
@kathodler Thanks for feedback! I will make sure to update synpress with metamask@10 until end of the week.
