### ISSUE TITLE
Trouble loading custom config file with Synpress 2.2.0

### ISSUE THREAD

**Issue by alexo382** [Synthetixio/synpress#492]
Hello again,

I'm having some trouble loading a custom config file, please see below:

Case 1: with `defineConfig` - cypress throws error on start
![Screenshot 2022-09-11 at 11 35 35](https://user-images.githubusercontent.com/6436419/189518847-a30a20a6-96bf-4fd9-8b98-fa9b223a603f.png)

Case 2: without `defineConfig` - cypress doesn't throw an error on start but when trying to run a spec
![Screenshot 2022-09-11 at 11 34 59](https://user-images.githubusercontent.com/6436419/189518836-b9533723-70c9-48c3-ab55-c75530464103.png)

In this instance, I tested both with the default CRA config and with CRACO and the result is the same. I couldn't find much about this in the Cypress issues either; it's strange because our config is the default config specified in the Synpress docs so I'm not really sure what I'm doing wrong.

Can you please take a look at this one @drptbl? A reproducible example can be found in this repo: https://github.com/alexo382/synpress-test/

Thanks a lot!

**Comment by drptbl** [comment]
Use js config, not ts.

**Comment by alexo382** [comment]
> Use js config, not ts.

I get the same errors when using .js :(

**Comment by drptbl** [comment]
@alexo382 please provide an example with javascript setup (as described in the readme), typescript is not supported yet (but planned)

**Comment by alexo382** [comment]
> @alexo382 please provide an example with javascript setup (as described in the readme), typescript is not supported yet (but planned)

Ah, my bad, I assumed Synpress had TS support due to the `tsconfig.json` required in the setup. Please take a look again here: https://github.com/alexo382/synpress-test/, the setup is now as described in the Readme.

Thanks again!

**Comment by drptbl** [comment]
Hey @alexo382,

I have fixed this for you:
https://github.com/drptbl/synpress-test/commit/71e77e2a0742e2864d2b38d7f4d5465c04d84fd2
https://github.com/drptbl/synpress-test/
^ take a look at my commits.

It was actually a very good issue. The problem was that you've not mirrored the whole synpress default config (which also required a little bit of changes) and instead has changed only things you wanted to change. I will make sure to mention this is the readme or add a support for merging configs to prevent it from happening in future.

Thanks,
Jakub.

**Comment by drptbl** [comment]
@alexo382 feel free to reopen this issue if it's still present.

thanks,
jakub.
