### ISSUE TITLE
docker-compose fails to load synthetixio/docker-e2e

### ISSUE THREAD

**Issue by ComradeAERGO** [Synthetixio/synpress#652]
In an attempt to understand how to make synpress run in the CI of my project, I cloned synpress's repo and tried to run the docker-compose.

I basically tried those two :
`./start-tests.sh`
`docker-compose --profile foundry up --build --exit-code-from synpress`

Both fail when it comes to load synthetixio/docker-e2e
<img width="1598" alt="image" src="https://user-images.githubusercontent.com/73408295/221203982-5a8ab8cc-d392-4024-9138-2339d41b2e09.png">

I also tried to pull it manually, without success
<img width="949" alt="image" src="https://user-images.githubusercontent.com/73408295/221204378-04ec481a-d527-4c39-9893-fbb0a67a1692.png">

As I read it could be a source of issues on M1 machines, I switched off buildkit in Docker Desktop Client
<img width="737" alt="image" src="https://user-images.githubusercontent.com/73408295/221215321-0a7f0228-0b4d-48ea-a7ed-97fa333e6dd3.png">

Any idea what could be going wrong ?

I'm quite new to Docker so I might have forgot something in the process.

My setup:
M1 Macbook on OS 13.0.1 Ventura
node 16.18.1

**Comment by AhmedIbrahim336** [comment]
Hi, @ComradeAERGO! 

I had the same issue as well on my M1 Macbook. 

It is happening because [synthetixio/docker-e2e](https://hub.docker.com/r/synthetixio/docker-e2e/tags) docker image only runs on `linux/amd64` base machine. That's why you are getting this error "docker image is not found" 


Read this article to know how to run this image on your MacBook "[Docker on Apple Silicon Mac: How to Run x86 Containers with Rosetta 2](https://levelup.gitconnected.com/docker-on-apple-silicon-mac-how-to-run-x86-containers-with-rosetta-2-4a679913a0d5)"

**Comment by drptbl** [comment]
Hi @ComradeAERGO,

As @AhmedIbrahim336 stated, can you try to update your fork and try again?
https://github.com/Synthetixio/synpress/pull/648/files

Fix for this should already be in place.

Thanks,
Jakub.

**Comment by ComradeAERGO** [comment]
Thanks a lot guys, it work now 👍
